@startuml Stack

skinparam {
    monochrome true
    padding 1
}
class TellerCore{
    +void Tick() override
    +void Update() override
}
class GameModule{
    +void Tick() override
    +void Update() override
}
class SceneModule{
    +void Tick() override
    +void Update() override
}
class Agent{
    +void Tick() override
    +void Update() override
}
class Editor{
    +void Tick() override
    +void Update() override
}

class CSVLoader{
}

class Episode{
}

class AnimationSequencer{}
class Animation{}


TellerCore *-- GameModule
TellerCore *-- Editor
GameModule *-- SceneModule
SceneModule *-- Agent
Agent - Episode
Episode - CSVLoader

AnimationSequencer *-- Animation
Animation -> Agent :callback
TellerCore *-- AnimationSequencer
@enduml